"""Create whiteboard_events table

Revision ID: 7b893d497d38
Revises: 
Create Date: 2025-10-03 10:34:06.994972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b893d497d38'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whiteboard_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whiteboard_events_id'), 'whiteboard_events', ['id'], unique=False)
    op.create_index(op.f('ix_whiteboard_events_room_id'), 'whiteboard_events', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whiteboard_events_room_id'), table_name='whiteboard_events')
    op.drop_index(op.f('ix_whiteboard_events_id'), table_name='whiteboard_events')
    op.drop_table('whiteboard_events')
    # ### end Alembic commands ###
